### ISSUE TITLE
ProtectedDebugStick say i use an old viersion (2.1.1) but i have the version 2.2.0 installed

### ISSUE THREAD

**Issue by Lubinrns** [MachiganMC/ProtectedDebugStick#16]
I don't know if the problem come of me or its a bug but i when i connect to my server a receive this message :
![image](https://github.com/MachiganMC/ProtectedDebugStick/assets/73492297/ba0f8489-f352-4e23-b536-672c9db5930f)

I have tried to remove the plugin, restart server, clear plugin data (delete ProtectedDebugStick folder) and restart the server but nothing change.
![image](https://github.com/MachiganMC/ProtectedDebugStick/assets/73492297/b0821cba-91be-4555-aa8f-7e3b436128f9)
I have 2.2.0 version installed.

**Comment by MachiganMC** [comment]
Hello, do you have the logs from the console please ?

**Comment by Lubinrns** [comment]
> Hello, do you have the logs from the console please ?

**Comment by MachiganMC** [comment]
I think you forgot something 😅

**Comment by MachiganMC** [comment]
Hello, I just check for the error and I found it. It will be fix in the next update, tahnks for the reporting

**Comment by Lubinrns** [comment]
Np, ty ^^
