### ISSUE TITLE
Update MineCraft 1.21

### ISSUE THREAD

**Issue by M0PAH** [MachiganMC/ProtectedDebugStick#21]
Is there going to be an update to 1.21 ?

**Comment by MachiganMC** [comment]
Hello, yes the plugin will have an 1.21 update when it will be possible and I'll have the time (so soon)

**Comment by MachiganMC** [comment]
Hello, I have implemented that in 27483dd04dd82c329665e4be9f2c5ba9bbd3d5d3
It will be added in the next update.
